### ISSUE TITLE
Slowness with simple 'max' signature

### ISSUE THREAD

**Issue by danpf** [sizmailov/pybind11-stubgen#60] opened 2021-09-10 21:37 UTC
Hello,
the signature regex seems to be getting stuck on a pretty simple signature of a pybind11 built module.

I'm not experienced with regex but I can provide a simple example for you:
(requires `pip install pebble`)

I think this is sort of mentioned in a few other issues (specifically #51 ) but I think the max signature which is pybind11 generated is slightly different.

If you don't think so, feel free to close this.

Thank you for your work on this library!

```

from pebble import ProcessPool
import re


def run_test(name, line):
    no_parentheses = r"[^()]*"
    parentheses_one_fold = r"({nopar}(\({nopar}\))?)*".format(nopar=no_parentheses)
    parentheses_two_fold = r"({nopar}(\({par1}\))?)*".format(par1=parentheses_one_fold, nopar=no_parentheses)
    parentheses_three_fold = r"({nopar}(\({par2}\))?)*".format(par2=parentheses_two_fold, nopar=no_parentheses)
    signature_regex = r"(\s*(?P<overload_number>\d+).)" \
                      r"?\s*{name}\s*\((?P<args>{balanced_parentheses})\)" \
                      r"\s*->\s*" \
                      r"(?P<rtype>[^\(\)]+)\s*".format(name=name,
                                                       balanced_parentheses=parentheses_three_fold)
    return re.match(signature_regex, line)

def main():
    test_subjects = (
            # typed
            ("max", "max( unsigned short int, unsigned short int )"),
            ("max", "max( long int, long int )"),
            ("max", "max(a: int, b: int)"),
            # example in docstring
            ("pss", 'myps = pss(banana, "HELLOBANANA", myproj::things::Thing1)'),
            ("pss", '    pss(banana, "HELLOBANANA", myproj::things::Thing1)'),
            )
    with ProcessPool(max_workers=5) as ppe:
        futures = []
        for name, line in test_subjects:
            futures.append(ppe.schedule(run_test, args=[name, line], timeout=5))
    for i, x in enumerate(futures):
        print(f"{x.exception}, {test_subjects[i][0]}\n{test_subjects[i][1]}")

if __name__ == "__main__":
    main()

```

yields:

```
<bound method Future.exception of <ProcessFuture at 0x7fe12e9a6e50 state=finished raised TimeoutError>>, max
max( unsigned short int, unsigned short int )
<bound method Future.exception of <ProcessFuture at 0x7fe12e9a6f70 state=finished returned NoneType>>, max
max( long int, long int )
<bound method Future.exception of <ProcessFuture at 0x7fe12e9b6070 state=finished returned NoneType>>, max
max(a: int, b: int)
<bound method Future.exception of <ProcessFuture at 0x7fe12e9b6130 state=finished returned NoneType>>, pss
myps = pss(banana, "HELLOBANANA", myproj::things::Thing1)
<bound method Future.exception of <ProcessFuture at 0x7fe12e9b61f0 state=finished raised TimeoutError>>, pss
    pss(banana, "HELLOBANANA", myproj::things::Thing1)
```

**Comment by sizmailov** [comment] 2021-09-17 11:36
Closed as duplicate of #51

**Closed by sizmailov** 2021-09-17 11:36 UTC
Labels: duplicate
