### ISSUE TITLE
Non-deterministic output for enums in python<=3.5

### ISSUE THREAD

**Issue by daltairwalter** [sizmailov/pybind11-stubgen#30] opened 2020-08-04 21:59 UTC
I am using version 0.3.5 and when I run stub generation multiple times on the same pyd file, the order of the enums changes in the results.

**Comment by sizmailov** [comment] 2020-08-04 23:41
`pybind11-stubgen` is primarily designed to deal with pybind11 modules, not `.pyd` files, so I guess this issue out of scope, sorry. You can have a better luck with `mypy.stubgen`. By the way which version of python do you use?

**Comment by sizmailov** [comment] 2020-08-04 23:49
Sorry, I confused `.pxd` for `.pyd` since both are exotic to me :)

Can you provide a minimal example? Which version of python do you use?

**Comment by daltairwalter** [comment] 2020-08-05 15:47
I am using python 3.5.4.  I attached a cxx example file and the output of two different invocations of pybind11-stubgen on the pyd that was created with this example.

[enumtest.zip](https://github.com/sizmailov/pybind11-stubgen/files/5029462/enumtest.zip)

**Comment by sizmailov** [comment] 2020-08-05 23:10
Order-preserving dictionaries are implementation detail of python 3.6 which become specification for python 3.7+ ([SO](https://stackoverflow.com/a/39980744/1741477)). In older versions order of elements is arbitrary and it's what you see. Definition order of attributes is available for introspection from python 3.6 (see [PEP 520](https://www.python.org/dev/peps/pep-0520)). 

I think there is no way to restore order of attributes definition prior python 3.6. The only thing that might be desirable for reproducible output is generating attributes/methods in lexicographical order in python<3.6. Would it suffice your needs? 

Note: lexicographical order might be inconsistent with actual definition.

**Comment by daltairwalter** [comment] 2020-08-05 23:54
I think lexicographical order would be an improvement, but definition order is really the ideal.

If this is working in python 3.7, I will try building my extensions an extra time in the updated python.  I imagine that sphinx will have the same issues if I manage to get sphinx working.

Thank you for looking into this and for building pybind11-stubgen - it has been very easy to use and helpful for me.

**Comment by sizmailov** [comment] 2020-08-06 12:38
I realized that even having ordered dicts everywhere on `pybind11-stubgen` side won't save from non-deterministic output since enum docstring generated by `pybind11` [uses](https://github.com/pybind/pybind11/blob/3e448c0b5e3abcd179781dd718df2bd2340ddb06/include/pybind11/pybind11.h#L1476-L1492) `dict` internally. I don't like the idea of shuffle "user-defined" strings. It would be hard to maintain and harden against unwanted reorder, and finally its needed only for python versions which are nearly [end-of-life](https://devguide.python.org/#status-of-python-branches). 

WRT to sphinx. I've managed `sphinx.autodoc` to work with pybind11 modules at some point with [a bit of extra work](https://github.com/sizmailov/pyxmolpp2/blob/f7dcac26051f1be448c05a6cc125745c8db343ad/docs/source/conf.py). Now I'm using `m.css` which [supports pybind11 modules out of box](https://mcss.mosra.cz/documentation/python/).

**Closed** 2020-08-06 12:38 UTC
Labels: wontfix
