### ISSUE TITLE
Function default argument with bound enum

### ISSUE THREAD

**Issue by jargonzombies** [sizmailov/pybind11-stubgen#52] opened 2020-11-15 16:19 UTC
Unfortunately, pybind generates an unhelpful docstring for this function with a default argument with a bound enum:

```c++
enum class Color {Red};

PYBIND11_MODULE(foo, m) {
  pybind11::enum_<Color> (m, "Color").value("Red", Color::Red);
  m.def("bar", [](Color) {}, pybind11::arg("a") = Color::Red);
}
```

```python
>>> help(foo.bar)
foo(...) method of builtins.PyCapsule instance
    bar(a: foo.Color = <Color.Red: 0>) -> None
```
To your credit, even though the default argument isn't even module qualified, your parsing doesn't trip over this. Unfortunately, it does classify the enum name `Color` as a module and adds it to the import statements at the top:

```python
import foo
import typing
import Color
```

Arguably, the onus is on pybind to write valid docstrings. But this could be fixed in two lines here:

```diff
@@ -744,7 +744,8 @@ class ModuleStubsGenerator(StubsGenerator):
         for f in self.free_functions:  # type: FreeFunctionStubsGenerator
             result |= f.get_involved_modules_names()

-        return set(result) - {"builtins", 'typing', self.module.__name__}
+        classnames = set(C.klass.__name__ for C in self.classes)
+        return set(result) - {"builtins", 'typing', self.module.__name__} - classnames

     def to_lines(self):  # type: () -> List[str]
```

Would you consider adding such a hack to enable the use of bound enums in the current form or reject it in favor of upstream work?

**Comment by sizmailov** [comment] 2020-11-15 16:58
Hi! 
This issue is essentially a duplicate of #36. I think it needs a more robust solution, although some hacks are unavoidable since everything here stands on shaky ground :crying_cat_face:

**Closed by sizmailov** 2020-11-15 16:58 UTC
